services:
  database:
    image: postgres:17.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - server_net

  server:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/server
    working_dir: /server
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - server_net
volumes:
  postgres_data:

networks:
  server_net:
